connector.name=modak
modak.jdbc-url=jdbc:postgresql://postgres:5432/postgres
modak.jdbc-user=postgres
modak.jdbc-password=modak
modak.fileio.s3.endpoint=http://rustfs:9000
modak.fileio.s3.path-style-access=true
modak.fileio.s3.access-key-id=rustfs-root-user
modak.fileio.s3.secret-access-key=rustfs-root-password
modak.fileio.client.region=us-east-1
