connector.name=tierdb
tierdb.jdbc-url=jdbc:postgresql://postgres:5432/postgres
tierdb.jdbc-user=postgres
tierdb.jdbc-password=tierdb
tierdb.fileio.s3.endpoint=http://rustfs:9000
tierdb.fileio.s3.path-style-access=true
tierdb.fileio.s3.access-key-id=rustfs-root-user
tierdb.fileio.s3.secret-access-key=rustfs-root-password
tierdb.fileio.client.region=us-east-1
